---
- hosts: all
  vars:
     - ansible_sudo_pass: "1234"
  user: ansible
  become: true
  connection: ssh
  tasks:
  
     - name: build docker
       shell: docker build -t demo34 /home/ansible/playbook
      
     - name: tag container latest
       shell: docker tag demo yadavashu/demo:latest
     
     - name: push prev container 
       shell: docker push yadavashu/demo:latest
   
     - name: create docker image
       shell: docker run -d --name cont_44 -p 8090:8080 yadavashu/demo:latest
